/**
 * @evjs/ev — config, plugin, and bundler types for the evjs framework.
 */

export type * from "@evjs/shared/manifest";
export {
  createPublicManifest,
  getClientRouteMatches,
  getClientRouteTarget,
  getServerRenderedPagePaths,
  getServerRenderedPaths,
  getServerRenderedRoutePaths,
  isRouteDerivedPage,
  isServerRenderedPage,
  linkBuildOutput,
  resolveRoutes,
} from "@evjs/shared/manifest";
export type {
  BundlerAdapter,
  BundlerBuildContext,
  BundlerBuildFacts,
  BundlerDevContext,
  BundlerDevController,
} from "./bundler.js";
export {
  type BuildOptions,
  build,
  type DevOptions,
  dev,
  type InspectBuildEntry,
  type InspectDiagnostic,
  type InspectFrameworkBuildOptions,
  type InspectFrameworkBuildResult,
  type InspectHtmlDocument,
  type InspectPageOutput,
  type InspectPageRoute,
  type InspectRouteFile,
  type InspectServerFunction,
  type InspectServerRoute,
  inspectFrameworkBuild,
  type PreparedFrameworkBuild,
  type PrepareFrameworkBuildOptions,
  prepareFrameworkBuild,
} from "./commands.js";
export {
  type AppConfig,
  type BuildResult,
  type BundlerCtx,
  type ClientManifest,
  CONFIG_DEFAULTS,
  type Config,
  type CrossOriginLoadingPolicy,
  type DefaultBundlerConfig,
  type DevConfig,
  type DevProxyRule,
  defineConfig,
  type EvBuildResult,
  type EvBundlerCtx,
  type EvConfig,
  type EvDocument,
  type EvPlugin,
  type EvPluginConfigContext,
  type EvPluginContext,
  type EvPluginHooks,
  type HtmlDocument,
  type HtmlDocumentInfo,
  type HtmlTransformContext,
  isMpa,
  type ManifestAssets,
  type OutputConfig,
  type PageConfig,
  type PageManifestEntry,
  type PageObjectConfig,
  type PageRoutingConfig,
  type PageRoutingLayoutConfig,
  type Plugin,
  type PluginConfigContext,
  type PluginContext,
  type PluginHooks,
  type ResolvedAppConfig,
  type ResolvedConfig,
  type ResolvedDevConfig,
  type ResolvedEvConfig,
  type ResolvedFunctionRuntimeConfig,
  type ResolvedOutputConfig,
  type ResolvedPageRoutingConfig,
  type ResolvedServerConfig,
  type ResolvedServerDevConfig,
  type ResolvedServerRscConfig,
  type ResolvedTransportConfig,
  type RouteEntry,
  type RoutingConfig,
  type RoutingMode,
  resolveConfig,
  type ServerConfig,
  type ServerDevConfig,
  type ServerFnEntry,
  type ServerManifest,
  type ServerRouteEntry,
  type ServerRscConfig,
  type TransportConfig,
} from "./config.js";
export {
  createDeploymentArtifact,
  createEdgeDeploymentFiles,
  createNodeDeploymentFiles,
  createStaticDeploymentFiles,
  type DeploymentApp,
  type DeploymentArtifact,
  type DeploymentArtifactOptions,
  type DeploymentPage,
  type DeploymentRoute,
  type DeploymentRsc,
  type DeploymentServer,
  type EdgeDeploymentAdapterOptions,
  type EdgeDeploymentFiles,
  edgeDeploymentAdapter,
  type NodeDeploymentAdapterOptions,
  type NodeDeploymentFiles,
  nodeDeploymentAdapter,
  type StaticDeploymentAdapterOptions,
  type StaticDeploymentCompatibility,
  type StaticDeploymentFiles,
  type StaticDeploymentUnsupportedCapability,
  staticDeploymentAdapter,
} from "./deployment.js";
export { type BuildHtmlOptions, buildHtml } from "./html.js";
export { type ConfigPatch, merge } from "./merge.js";
