import type { Dirent } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import type { PageRouteNode } from "@evjs/shared/manifest";
import {
  PAGE_ROUTE_CONVENTION_DOCS_URL,
  PAGE_ROUTE_CONVENTION_SUMMARY,
} from "./page-route-conventions.js";
import { sortPageRoutes } from "./page-route-order.js";
import { toProjectPath } from "./utils.js";

export const PAGE_ROUTE_TYPES_FILE = "evjs-route-types.d.ts";
export const PAGE_ROUTE_TYPES_MARKER =
  "// This file is generated by evjs. Do not edit it directly.";
export const PAGE_ROUTE_TYPES_USAGE_HINT =
  "// Do not import this file from application code; include its directory in tsconfig instead.";
export const PAGE_ROUTE_TYPES_CONVENTION_HINT = `// Page route file convention: ${PAGE_ROUTE_CONVENTION_SUMMARY}. See ${PAGE_ROUTE_CONVENTION_DOCS_URL}`;
export const PAGE_ROUTE_TYPES_REGISTER_MODULE = "@evjs/client";
export const PAGE_ROUTE_TYPES_HELPER_MODULE =
  "@evjs/client/internal/route-types";
const PAGE_ROUTE_TYPES_CLEANUP_SKIP_DIRS = new Set([
  ".git",
  ".turbo",
  "dist",
  "node_modules",
]);

export interface GeneratePageRouteTypesOptions {
  routes: PageRouteNode[];
  importBaseDir?: string;
  clientModule?: string;
}

export interface PageRouteTypesPath {
  dir: string;
  file: string;
  importBaseDir: string;
}

export function generatePageRouteTypes({
  routes,
  importBaseDir,
  clientModule = PAGE_ROUTE_TYPES_REGISTER_MODULE,
}: GeneratePageRouteTypesOptions): string {
  const sortedRoutes = sortPageRoutes(
    routes.filter((route) => route.kind !== "layout"),
  );
  const usedImportNames = new Set<string>();
  const usedRouteTypeNames = new Set<string>();
  const routeTypes = sortedRoutes.map((route) => {
    const importName = createUniqueIdentifier(
      createPageModuleIdentifier(route.id),
      usedImportNames,
    );
    return {
      ...route,
      typeImport: toTypeImportSpecifier(route.module, importBaseDir),
      importName,
      routeTypeName: createUniqueIdentifier(
        createRouteTypeIdentifier(route.id),
        usedRouteTypeNames,
      ),
    };
  });

  const imports = routeTypes.map(
    (route) =>
      `import type * as ${route.importName} from ${JSON.stringify(route.typeImport)};`,
  );

  const routeTypeDeclarations = routeTypes.map(
    (route) =>
      `  ${route.routeTypeName}: { id: ${JSON.stringify(route.id)}; path: ${JSON.stringify(route.path)}; module: typeof ${route.importName} };`,
  );

  return [
    "/* eslint-disable */",
    PAGE_ROUTE_TYPES_MARKER,
    PAGE_ROUTE_TYPES_USAGE_HINT,
    PAGE_ROUTE_TYPES_CONVENTION_HINT,
    `import type { CreatePageRouteRegister } from ${JSON.stringify(PAGE_ROUTE_TYPES_HELPER_MODULE)};`,
    ...imports,
    "",
    "interface EvPageRoutes {",
    ...routeTypeDeclarations,
    "}",
    "",
    `declare module ${JSON.stringify(clientModule)} {`,
    "  interface Register extends CreatePageRouteRegister<EvPageRoutes> {}",
    "}",
    "",
    "export {};",
    "",
  ].join("\n");
}

export function getPageRouteTypesPath(
  cwd: string,
  routingDir: string,
): PageRouteTypesPath {
  const absoluteRouteDir = path.resolve(cwd, routingDir);
  const dir = path.dirname(absoluteRouteDir);
  return {
    dir,
    file: path.join(dir, PAGE_ROUTE_TYPES_FILE),
    importBaseDir: toProjectPath(cwd, dir),
  };
}

export async function collectGeneratedPageRouteTypeFiles(
  cwd: string,
): Promise<string[]> {
  const files: string[] = [];

  async function visit(dir: string): Promise<void> {
    let entries: Dirent<string>[];
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return;
      throw err;
    }

    for (const entry of entries) {
      const absolute = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (PAGE_ROUTE_TYPES_CLEANUP_SKIP_DIRS.has(entry.name)) continue;
        await visit(absolute);
        continue;
      }

      if (!entry.isFile() || entry.name !== PAGE_ROUTE_TYPES_FILE) continue;
      if (await isGeneratedPageRouteTypesFile(absolute)) {
        files.push(absolute);
      }
    }
  }

  await visit(cwd);
  return files.sort();
}

export async function isGeneratedPageRouteTypesFile(
  file: string,
): Promise<boolean> {
  try {
    const source = await fs.readFile(file, "utf-8");
    return source.includes(PAGE_ROUTE_TYPES_MARKER);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw err;
  }
}

export async function writePageRouteTypesIfChanged(
  file: string,
  source: string,
): Promise<void> {
  try {
    const current = await fs.readFile(file, "utf-8");
    if (current === source) return;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }

  await fs.writeFile(file, source, "utf-8");
}

function createPageModuleIdentifier(routeId: string): string {
  return `EvPage_${toSafeIdentifier(routeId)}`;
}

function createRouteTypeIdentifier(routeId: string): string {
  return `EvRoute_${toSafeIdentifier(routeId)}`;
}

function createUniqueIdentifier(
  baseName: string,
  usedNames: Set<string>,
): string {
  let candidate = baseName;
  let suffix = 2;

  while (usedNames.has(candidate)) {
    candidate = `${baseName}_${suffix}`;
    suffix++;
  }

  usedNames.add(candidate);
  return candidate;
}

function toSafeIdentifier(value: string): string {
  const safe = value.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[a-zA-Z_$]/.test(safe) ? safe : `_${safe}`;
}

function toTypeImportSpecifier(module: string, importBaseDir?: string): string {
  const extensionless = module.replace(/\.[cm]?[jt]sx?$/, "");
  if (!importBaseDir || !module.startsWith("./")) return extensionless;

  const relative = pathRelative(importBaseDir, extensionless);
  return relative.startsWith(".") ? relative : `./${relative}`;
}

function pathRelative(fromDir: string, module: string): string {
  const fromParts = fromDir.replace(/^\.\//, "").split("/").filter(Boolean);
  const moduleParts = module.replace(/^\.\//, "").split("/").filter(Boolean);

  while (
    fromParts.length > 0 &&
    moduleParts.length > 0 &&
    fromParts[0] === moduleParts[0]
  ) {
    fromParts.shift();
    moduleParts.shift();
  }

  return [...fromParts.map(() => ".."), ...moduleParts].join("/") || ".";
}
